{% set name = "flake8-broken-line" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e2c6a17f8d9a129e99c1320fce89b33843e2963871025c4c2bb7b8b8d8732a85

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.5.0
    - python >=3.8
  run:
    - flake8 >5
    - python >=3.8

test:
  commands:
    - pip check
    - flake8 --version | grep flake8-broken-line
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/wemake-services/flake8-broken-line
  summary: Flake8 plugin to forbid backslashes for line breaks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
